name: Deploy React App

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        # 1. Говорим гитхабу выполнять все команды внутри папки с проектом
        working-directory: ./cars-project 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install # Используем обычный install для надежности

      - name: Build project
        run: CI=false npm run build
        env:
          PUBLIC_URL: './'

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # 2. Указываем правильный путь к готовой сборке
          path: ./cars-project/build 

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
