name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # или master, смотря как называется ваша главная ветка

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Стабильная версия для CRA

      - name: Install dependencies
        run: npm ci # Чистая установка пакетов без изменения package-lock.json

      - name: Build project
        run: npm run build
        env:
          CI: false # Отключает строгий режим, чтобы проект собирался даже с варнингами (предупреждениями) в коде

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build' # Для create-react-app папка сборки называется build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
